### ISSUE TITLE
Portfolio: accessibility

### ISSUE THREAD

**Issue by egichuhis** [egichuhis/Edwin-Portfolio#18]
Hello,

I am repeating this module. I have already completed these sections. Feel free to check my project.

Cheers!

**Comment by franclobo** [comment]
Hi @egichuhis, 

# STATUS: APPROVED 😃 

![gif-good-job-79](https://user-images.githubusercontent.com/58642949/229783192-b8f32aa2-90bc-4572-b061-5e4268e3e930.gif)

Your project is complete!  It has been approved on [Feb 2nd](https://github.com/egichuhis/Edwin-Portfolio/pull/9). There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Good communication with CR ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
